### ISSUE TITLE
Custom space size

### ISSUE THREAD

**Issue by TadaCZE** [MasterQ32/kristall#147]
I think kristall should allow for custom space size, the default is too big

**Comment by mikejzx** [comment]
Could you try elaborate a little more? "Custom space size" isn't very descriptive so people such as myself don't really know what exactly you're referring to :wink: 

Some screenshots of what you're talking about would be very helpful

**Comment by kkabrams** [comment]
![2021-03-04-142142_298x116_scrot](https://user-images.githubusercontent.com/49476732/110025548-21277d80-7cf5-11eb-8e6c-6368e9079967.png) Pretty sure they mean this hilighted space between words. It does seem a bit wide.

**Comment by MasterQ32** [comment]
This might be a side effect of using justified text instead of left-aligned one

**Comment by kkabrams** [comment]
Looks like it might just be the font choice. Switched from "San Serif" to "Unifont" and the spaces were normal-looking.

**Comment by mikejzx** [comment]
@kkabrams 
Are you running a newer build of kristall? (e.g nightly from [random-projects.net](https://kristall.random-projects.net) or built from source yourself)

There was a font issue previously where the _emoji font_ would take precedence over the main font ([see](https://github.com/MasterQ32/kristall/issues/166#issuecomment-784498588)) and create strange artefacts including large word spacing like what you've shown. This should be fixed as of #173 as a fallback font was added to prevent this from happening. You seem to have been seeing this issue so you might be on an old build

The text justification should only be a factor if the text was in a _paragraph, list, etc_. Headings never get justified because it looks weird 😆

**Comment by MasterQ32** [comment]
@TadaCZE can you confirm that changing the font also fixes weird spacing?

**Comment by bgvaughan** [comment]
I'm still seeing this issue, on Kristall 0.4 on Debian. Most of the font options default to  "Sans",  and have enormous spaces. Switching Sans to the DejaVu fonts corrects the size of the spacing. (Sans is an alias, and on my system should be set to DejaVu; I confirmed that with fc-match).
